### ISSUE TITLE
Problem with Sublime project generation

### ISSUE THREAD

**Issue by raffeyang** [ssoher/com.sarpersoher.ide.sublimetext#2]
When the Unity project file name has spaces,the *.sublime-workspace generation can be problematic.

![CleanShot 2023-01-09 at 23 58 35@2x](https://user-images.githubusercontent.com/7557357/211351751-8b9ea552-47ff-4e03-97a5-ab1a7bd218db.png)
![CleanShot 2023-01-09 at 23 59 33@2x](https://user-images.githubusercontent.com/7557357/211351959-3dac8eb1-d780-46c0-b3b2-96ba626a2b92.png)
The file 'Framework.sublime-workspace' should be 'VR Interaction Framework.sublime-workspace'

**Comment by ssoher** [comment]
Thanks, great find! Such a simple bug too. Please pull the last commit for the fix.
