### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by mkonstapel** [ssoher/com.sarpersoher.ide.sublimetext#3]
It currently does not find/recognize Sublime Text on Linux, but I got it to work with two small changes:

- add `sublime_text` to `k_SupportedFileNames`
- add `/opt/sublime_text/sublime_text` or `/usr/bin/subl` to `possiblePaths`

**Comment by ssoher** [comment]
Thanks! Just added your changes. I have no access to a linux machine or VM atm, could you please confirm the last commit works before closing this issue?

**Comment by mkonstapel** [comment]
Yes, that works! :+1:
