### ISSUE TITLE
LSP-Omnisharp crashes on Linux

### ISSUE THREAD

**Issue by LexouDuck** [ssoher/com.sarpersoher.ide.sublimetext#4]
Hello,

This Unity package does not seem to work nicely with LSP-Omnisharp on Linux platforms (to be precise I am using Pop-OS v22.04 LTS, a derivative of Ubuntu).

Note that I have LSP-Omnisharp working fine in any normal SublimeText instance, but this package seems to create a special installation of SublimeText specific to Unity (whereas my normal SublimeText installation stores its config in `~/.config/sublime-text`, this Unity-specific installation has its config in `~/.var/app/com.unity.UnityHub/config/sublime-text`).

Here is what happens when I open an instance of SublimeText via Unity:
![image](https://user-images.githubusercontent.com/35985773/234006226-492b8c24-8d24-4da9-a01d-2845e4a51183.png)
And here is what is shown in the SublimeText console:
```
plugins loaded
LSP: OmniSharp crashed (1 / 5 times in the last 180.0 seconds), exit code 255, exception: None
LSP: OmniSharp crashed (2 / 5 times in the last 180.0 seconds), exit code 255, exception: None
LSP: OmniSharp crashed (3 / 5 times in the last 180.0 seconds), exit code 255, exception: None
LSP: OmniSharp crashed (4 / 5 times in the last 180.0 seconds), exit code 255, exception: None
LSP: OmniSharp crashed (5 / 5 times in the last 180.0 seconds), exit code 255, exception: None
Package Control: Skipping automatic upgrade, last run at 2023-04-24 14:52:54, next run at 2023-04-24 15:52:54 or after
```

**Comment by ssoher** [comment]
I have no way of testing this package on Linux, I'm not doing anything specific on Linux platforms, never create a specific installation of Sublime or anything of that sort. I'm sorry I can't be of any more help.
