### ISSUE TITLE
Release .unitypackage file 

### ISSUE THREAD

**Issue by Mohammad9760** [ssoher/com.sarpersoher.ide.sublimetext#5]
hey, I just love this package. just what I wanted!
but I don't want to clone the repository everytime (install from git URL in the package manager). it'd be really handy if you have a unitypackage file in the releases of this repo so that we can download it and keep it for when we need to create a new project.
thanks.

**Comment by ssoher** [comment]
Hey, sure, I mean you could already take the package files from `Library/PackageCache` and put it in a project to create a unitypackage but I've done it for you, you can find the unitypackage file in the releases. Cheers.

https://github.com/ssoher/com.sarpersoher.ide.sublimetext/releases/tag/v1.0

**Comment by Mohammad9760** [comment]
lovely! thank you man.
